apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reactdeploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: confound
    spec:
      containers:
        - name: reactfe
          image: 620835497377.dkr.ecr.eu-west-1.amazonaws.com/reactfe:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.5"
            requests:
              cpu: "0.25"
          ports:
            - containerPort: 80
